apiVersion: k3d.io/v1alpha3
kind: Simple

name: dev

servers: 1

ports:
- port: 8080:80
  nodeFilters:
  - loadbalancer

options:
  k3s:
    extraArgs:
    - arg: --kube-apiserver-arg=allow-privileged=true
      nodeFilters:
      - server:*
