apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql

spec:
  storageClassName: default
  resources:
    requests:
      storage: 4Gi
    limits:
      storage: 4Gi
  accessModes:
  - ReadWriteOnce
