apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default

# AWS EBS CSI driver will provision Persistent Volumes automatically
# when PVCs are created.
provisioner: ebs.csi.aws.com

allowVolumeExpansion: true
parameters:
  type: gp3
  csi.storage.k8s.io/fstype: ext4

volumeBindingMode: Immediate
reclaimPolicy: Delete
